services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=ejabberd
      - POSTGRES_PASSWORD=ejabberd
      - POSTGRES_DB=ejabberd
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg.sql:/docker-entrypoint-initdb.d/pg.sql
    networks:
      - default
  main:
    # https://github.com/processone/docker-ejabberd/tree/master/ecs
    image: ejabberd/ecs
    platform: linux/amd64
    container_name: ejabberd
    # https://docs.ejabberd.im/archive/old/#acme
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
      - "443:443"
      - "80:5280"
    volumes:
      - ./deploy.ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./conf/certs:/home/ejabberd/conf/certs/:ro
      - ./conf/secret.jwk:/home/ejabberd/conf/secret.jwk:ro
      - ejabberd_db:/home/ejabberd/database
      - ./setup-ejabberd.sh:/opt/setup-ejabberd.sh
    networks:
      - default
    depends_on:
      - postgres
    entrypoint: [ "/bin/sh", "-c", "/opt/setup-ejabberd.sh && ejabberdctl foreground" ]
    user: root

volumes:
  ejabberd_db:
  postgres_data:

networks:
  default:
    driver: bridge
    name: ejabberd