services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=ejabberd
      - POSTGRES_PASSWORD=ejabberd
      - POSTGRES_DB=ejabberd
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg.sql:/docker-entrypoint-initdb.d/pg.sql
    networks:
      - ejabberd-network
  main:
    image: ejabberd/ecs
    container_name: ejabberd
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5280:5280"
      - "5443:5443"
    volumes:
      - ./ejabberd.yml:/home/ejabberd/conf/ejabberd.yml:ro
      - ./conf/certs:/home/ejabberd/conf/certs/:ro
      - ejabbered_db:/home/ejabberd/database
      - ./setup-ejabberd.sh:/opt/setup-ejabberd.sh
    networks:
      - ejabberd-network
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "-c", "/opt/setup-ejabberd.sh && ejabberdctl foreground"]
    user: root
volumes:
  ejabbered_db:
  postgres_data:

networks:
  ejabberd-network:
    driver: bridge 
    ipam:
      config:
        - subnet: 172.21.0.0/16  # trusted ip range; localhost clients use this subnet for ejabberd connection 